### ISSUE TITLE
General failure

### ISSUE THREAD

**Issue by ain** [jonschlinkert/add-banner#4]
**Step to reproduce**:
1. Create `banner.js`:
   
   ``` js
   var banner = require('add-banner');
   console.log('Adding banner to smartbanner.min.js');
   banner('./dist/smartbanner.min.js', {username: 'ain'});
   ```
2. Create NPM script `bannerise` with `node banner.js`
3. Run `npm run bannerise`

**What happens**:

```
$ npm run bannerise

> smartbanner.js@0.0.1 bannerise /Users/ain/Documents/projects/smartbanner.js
> node banner.js

Adding banner to smartbanner.min.js
```

Nothing is written to `dist/smartbanner.min.js`.

**What should happen**: default banner should be written to `dist/smartbanner.min.js` in respect to `package.json`.

**Platform**:

```
$ node --version
v6.2.0
```

**Comment by ain** [comment]
My bad. One has to handle `banner()` output manually.

Module could use a CLI in a `bin/` to automate this for the NPM scripts.

**Comment by jonschlinkert** [comment]
> Module could use a CLI in a bin/ to automate this for the NPM scripts.

I was going to say that in the tweet, I agree. I thought I did add a CLI, I guess not
