### ISSUE TITLE
New release with updated README, CLI

### ISSUE THREAD

**Issue by ain** [jonschlinkert/add-banner#7]
Hey @jonschlinkert, just creating this reminder for you to mark the fact that the README isn't currently up to date with the Verb source and there's no release with CLI. 

Version should probably bump to `0.2.0`?

**Comment by jonschlinkert** [comment]
I'll try to do this sometime today

**Comment by ain** [comment]
[1.0.0](https://github.com/jonschlinkert/add-banner/releases/tag/1.0.0) released, closing.
